-- create
-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 06:15:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Food` (
  `name` VARCHAR(45) NOT NULL,
  `diet` VARCHAR(45) NOT NULL,
  `prep_time` INT NOT NULL,
  `cook_time` INT NOT NULL,
  `flavour_profile` VARCHAR(45) NULL,
  `course` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ingredients` (
  `idIngredients` INT NOT NULL,
  `Ingredients` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIngredients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Place` (
  `idPlace` INT NOT NULL,
  `state` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `Food_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlace`, `Food_name`),
  INDEX `fk_Place_Food_idx` (`Food_name` ASC),
  CONSTRAINT `fk_Place_Food`
    FOREIGN KEY (`Food_name`)
    REFERENCES `Food` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ingredients_has_Food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ingredients_has_Food` (
  `Ingredients_idIngredients` INT NOT NULL,
  `Food_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Ingredients_idIngredients`, `Food_name`),
  INDEX `fk_Ingredients_has_Food_Food1_idx` (`Food_name` ASC),
  INDEX `fk_Ingredients_has_Food_Ingredients1_idx` (`Ingredients_idIngredients` ASC),
  CONSTRAINT `fk_Ingredients_has_Food_Ingredients1`
    FOREIGN KEY (`Ingredients_idIngredients`)
    REFERENCES `Ingredients` (`idIngredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredients_has_Food_Food1`
    FOREIGN KEY (`Food_name`)
    REFERENCES `Food` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

