-- create
-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 04:46:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Person` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `date_file_created` DATE NOT NULL,
  `borrowed_before` TINYINT NOT NULL,
  `flagged` TINYINT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contact_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Contact_Info` (
  `contactID` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `cell_phone` VARCHAR(45) NOT NULL,
  `home_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`contactID`),
  CONSTRAINT `fk_Contact_Info_Person`
    FOREIGN KEY (`user_id`)
    REFERENCES `Person` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Manufacturer` (
  `idManufacturer` INT NOT NULL AUTO_INCREMENT,
  `manufac_name` VARCHAR(45) NOT NULL,
  `manufac_country` VARCHAR(45) NOT NULL,
  `model_number` VARCHAR(45) NOT NULL,
  `srange` FLOAT NOT NULL,
  `sweight` FLOAT NOT NULL,
  `topspeed` FLOAT NOT NULL,
  PRIMARY KEY (`idManufacturer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scooters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Scooters` (
  `idScooter` INT NOT NULL AUTO_INCREMENT,
  `scondition` VARCHAR(85) NOT NULL,
  `idManufacturer` INT NOT NULL,
  PRIMARY KEY (`idScooter`),
  INDEX `fk_Scooters_Manufacturer1_idx` (`idManufacturer` ASC),
  CONSTRAINT `fk_Scooters_Manufacturer1`
    FOREIGN KEY (`idManufacturer`)
    REFERENCES `Manufacturer` (`idManufacturer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Returned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Returned` (
  `idReturn` INT NOT NULL AUTO_INCREMENT,
  `date_returned` DATE NOT NULL,
  `is_late` TINYINT NOT NULL,
  `damaged` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReturn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Borrowed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Borrowed` (
  `borrow_id` INT NOT NULL AUTO_INCREMENT,
  `borrow_date` DATE NOT NULL,
  `return_date` DATE NOT NULL,
  `idScooter` INT NOT NULL,
  `returned` TINYINT NOT NULL,
  `user_id` INT NOT NULL,
  `idReturn` INT NOT NULL,
  PRIMARY KEY (`borrow_id`, `idScooter`, `user_id`, `idReturn`),
  INDEX `fk_Borrowed_Scooters1_idx` (`idScooter` ASC),
  INDEX `fk_Borrowed_Person1_idx` (`user_id` ASC),
  INDEX `fk_Borrowed_Return1_idx` (`idReturn` ASC),
  CONSTRAINT `fk_Borrowed_Scooters1`
    FOREIGN KEY (`idScooter`)
    REFERENCES `Scooters` (`idScooter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Borrowed_Person1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Person` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Borrowed_Return1`
    FOREIGN KEY (`idReturn`)
    REFERENCES `Returned` (`idReturn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Freeform_notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Freeform_notes` (
  `freeformID` INT NOT NULL AUTO_INCREMENT,
  `borrow_id` INT NOT NULL,
  `notes` VARCHAR(85) NOT NULL,
  `return_condition` VARCHAR(45) NOT NULL,
  `malfunction` VARCHAR(45) NULL,
  `other` VARCHAR(45) NULL,
  PRIMARY KEY (`freeformID`),
  INDEX `fk_Freeform_notes_Borrowed1_idx` (`borrow_id` ASC),
  CONSTRAINT `fk_Freeform_notes_Borrowed1`
    FOREIGN KEY (`borrow_id`)
    REFERENCES `Borrowed` (`borrow_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Referral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Referral` (
  `referID` INT NOT NULL AUTO_INCREMENT,
  `user_referredID` INT NOT NULL,
  `name_of_borrower` VARCHAR(45) NOT NULL,
  `name_of_referrer` VARCHAR(45) NOT NULL,
  `referrerID` INT NOT NULL,
  PRIMARY KEY (`referID`, `user_referredID`, `referrerID`),
  INDEX `fk_Referral_Person1_idx` (`user_referredID` ASC),
  INDEX `fk_Referral_Person2_idx` (`referrerID` ASC),
  CONSTRAINT `fk_Referral_Person1`
    FOREIGN KEY (`user_referredID`)
    REFERENCES `Person` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Referral_Person2`
    FOREIGN KEY (`referrerID`)
    REFERENCES `Person` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
